### ISSUE TITLE
No Boosting giving error

### ISSUE THREAD

**Issue by rodrigoazs** [boost-starai/BoostSRL#16]
Hello,

When I set the -noBoost paramenter I am getting the following error:

`Exception in thread "main" edu.wisc.cs.will.Utils.WILLthrownError: 
 Probability was not set
	at edu.wisc.cs.will.Utils.Utils.error(Utils.java:484)
	at edu.wisc.cs.will.Boosting.RDN.RegressionRDNExample.getProbOfExample(RegressionRDNExample.java:176)
	at edu.wisc.cs.will.ILP.Regression.RegressionInfoHolderForRDN.populateExamples(RegressionInfoHolderForRDN.java:111)
	at edu.wisc.cs.will.ILP.SingleClauseNode.getRegressionInfoHolder(SingleClauseNode.java:1840)
	at edu.wisc.cs.will.ILP.SingleClauseNode.regressionFit(SingleClauseNode.java:1503)
	at edu.wisc.cs.will.ILP.SingleClauseNode.regressionFit(SingleClauseNode.java:1405)
	at edu.wisc.cs.will.ILP.ScoreRegressionNode.scoreThisNode(ScoreRegressionNode.java:35)
	at edu.wisc.cs.will.stdAIsearch.OpenList.insertByScoreIntoOpenList(OpenList.java:107)
	at edu.wisc.cs.will.stdAIsearch.OpenList.insertByScoreIntoOpenList(OpenList.java:216)
	at edu.wisc.cs.will.ILP.InitializeILPsearchSpace.initializeOpen(InitializeILPsearchSpace.java:187)
	at edu.wisc.cs.will.stdAIsearch.StateBasedSearchTask.initialize(StateBasedSearchTask.java:373)
	at edu.wisc.cs.will.stdAIsearch.StateBasedSearchTask.performSearchIteration(StateBasedSearchTask.java:505)
	at edu.wisc.cs.will.stdAIsearch.StateBasedSearchTask.performSearch(StateBasedSearchTask.java:440)
	at edu.wisc.cs.will.ILP.LearnOneClause.performSearch(LearnOneClause.java:1684)
	at edu.wisc.cs.will.ILP.LearnOneClause.performSearch(LearnOneClause.java:1708)
	at edu.wisc.cs.will.ILP.ILPouterLoop.executeOuterLoop(ILPouterLoop.java:686)
	at edu.wisc.cs.will.Boosting.RDN.LearnBoostedRDN.getWILLTree(LearnBoostedRDN.java:396)
	at edu.wisc.cs.will.Boosting.RDN.LearnBoostedRDN.learnRDN(LearnBoostedRDN.java:234)
	at edu.wisc.cs.will.Boosting.RDN.LearnBoostedRDN.learnNextModel(LearnBoostedRDN.java:129)
	at edu.wisc.cs.will.Boosting.RDN.RunBoostedRDN.learn(RunBoostedRDN.java:390)
	at edu.wisc.cs.will.Boosting.Common.RunBoostedModels.learnModel(RunBoostedModels.java:77)
	at edu.wisc.cs.will.Boosting.RDN.RunBoostedRDN.runJob(RunBoostedRDN.java:42)
	at edu.wisc.cs.will.Boosting.Common.RunBoostedModels.main(RunBoostedModels.java:220)
`

What am I doing wrong?

Thank you.

**Comment by batflyer** [comment]
Hey @rodrigoazs, `-noBoost` has been broken since before we began using git. I don't think it's anything you're doing wrong, fixing it is on the list of TODOs.

**Comment by boost-starai** [comment]
A suggestion is that you could instead run the code with numTrees set to 1 and maxTreeDepth to a larger number say 6-10. This will make sure that you still learn one regression tree.

We will fix this and push the code out in the next week. Thanks for bringing this to our attention.

Thanks
Sriraam

On Apr 21, 2018, at 6:29 PM, Alexander L. Hayes <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @rodrigoazs<https://github.com/rodrigoazs>, -noBoost has been broken since before we began using git. I don't think it's anything you're doing wrong, fixing it is on the list of TODOs.

**Comment by rodrigoazs** [comment]
I was about to ask if they were equivalent. Thank you.
