### ISSUE TITLE
Get error when the predicate name is "length".

### ISSUE THREAD

**Issue by harshakokel** [boost-starai/BoostSRL#33]
Face this error during precompute.

```
%    No need to compress since small: precomputed.txt
Exception in thread "main" edu.wisc.cs.will.Utils.WILLthrownError: 
 First argument cannot be a variable: length(Part, Y)
    at edu.wisc.cs.will.Utils.Utils.error(Utils.java:482)
    at edu.wisc.cs.will.FOPC.BuiltinProcedurallyDefinedPredicateHandler.handle(BuiltinProcedurallyDefinedPredicateHandler.java:628)
    at edu.wisc.cs.will.ResThmProver.HornClauseProverChildrenGenerator.collectChildrenActual(HornClauseProverChildrenGenerator.java:1001)
    at edu.wisc.cs.will.ResThmProver.HornClauseProverChildrenGenerator.collectChildren(HornClauseProverChildrenGenerator.java:276)
    at edu.wisc.cs.will.ResThmProver.HornClauseProverChildrenGenerator.collectChildren(HornClauseProverChildrenGenerator.java:1)
    at edu.wisc.cs.will.stdAIsearch.StateBasedSearchTask.search(StateBasedSearchTask.java:602)
    at edu.wisc.cs.will.stdAIsearch.StateBasedSearchTask.performSearchIteration(StateBasedSearchTask.java:507)
    at edu.wisc.cs.will.stdAIsearch.StateBasedSearchTask.performSearch(StateBasedSearchTask.java:440)
    at edu.wisc.cs.will.ResThmProver.HornClauseProver.prove(HornClauseProver.java:227)
    at edu.wisc.cs.will.ILP.Precompute.createPrecomputedFile(Precompute.java:237)
    at edu.wisc.cs.will.ILP.Precompute.processPrecomputeSpecifications(Precompute.java:91)
    at edu.wisc.cs.will.ILP.LearnOneClause.initialize(LearnOneClause.java:1271)
    at edu.wisc.cs.will.ILP.ILPouterLoop.initialize(ILPouterLoop.java:1358)
    at edu.wisc.cs.will.Boosting.RDN.WILLSetup.setup(WILLSetup.java:261)
    at edu.wisc.cs.will.Boosting.Common.RunBoostedModels.setupWILLForTrain(RunBoostedModels.java:88)
    at edu.wisc.cs.will.Boosting.Common.RunBoostedModels.learnModel(RunBoostedModels.java:78)
    at edu.wisc.cs.will.Boosting.RDN.RunBoostedRDN.runJob(RunBoostedRDN.java:42)
    at edu.wisc.cs.will.Boosting.Common.RunBoostedModels.main(RunBoostedModels.java:307)
```

**Comment by harshakokel** [comment]
@nandhiniramanan5  confirmed that length is an inbuilt predicate, so it cannot be used in the data.
